version: 2.1

jobs:
  build:
    docker:
      - image: node:20-alpine
    working_directory: ~/profile

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - run:
          name: Build React app
          command: |
            REACT_APP_FIREBASE_KEY="${REACT_APP_FIREBASE_KEY}" \
            REACT_APP_FIREBASE_DOMAIN="${REACT_APP_FIREBASE_DOMAIN}" \
            REACT_APP_FIREBASE_DB="${REACT_APP_FIREBASE_DB}" \
            REACT_APP_FIREBASE_PROJECT_ID="${REACT_APP_FIREBASE_PROJECT_ID}" \
            REACT_APP_FIREBASE_BUCKET="${REACT_APP_FIREBASE_BUCKET}" \
            REACT_APP_FIREBASE_MSG_SENDER_ID="${REACT_APP_FIREBASE_MSG_SENDER_ID}" \
            REACT_APP_FIREBASE_APP_ID="${REACT_APP_FIREBASE_APP_ID}" \
            yarn build

      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: cimg/base:stable
    working_directory: ~/profile

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Setup SSH Key
          command: |
            mkdir -p ~/.ssh
            echo -e "$EC2_SSH_KEY" > ~/.ssh/ec2_key.pem
            chmod 600 ~/.ssh/ec2_key.pem

      - run:
          name: Copy build folder to EC2
          command: |
            scp -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no -r ./build "$EC2_USER@$EC2_HOST:/home/ubuntu/profile"

      - run:
          name: Restart Docker container on EC2
          command: |
            ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST \<< 'EOF'
              cd /home/ubuntu/profile
              docker stop container-profile || true
              docker rm container-profile || true
              docker build --no-cache -t profile .
              docker run -d --name container-profile -p 127.0.0.1:8080:80 profile
            EOF

workflows:
  build-and-deploy:
    jobs:
      - build:
          context:
            - profile-ci-context
      - deploy:
          requires:
            - build
